# Lessons Learned: Azure AD Suspicious Sign-on

## 1. Anomaly does not equal compromise

Behavioral detections identify deviation from a baseline. The analyst must determine whether the deviation is malicious, operational, or caused by incomplete telemetry.

## 2. The exact detection trigger matters

Knowing whether the novelty came from IP, location, device, application, or a combination of attributes can substantially reduce investigation time. Detection platforms should expose the contributing features whenever possible.

## 3. City-level geolocation is weak evidence

A single public IP may map to nearby cities over time. When the IP and country remain stable, a city-only change should be treated cautiously unless supported by other risk factors.

## 4. Historical consistency is powerful

A 30-day timeline can quickly reveal whether an IP, application, browser, or access pattern is established. Extend the baseline when the account is infrequently used.

## 5. MFA evidence must be interpreted correctly

A token claim satisfying MFA is a legitimate authentication outcome. It means that a new challenge was unnecessary for that request, not that MFA was bypassed.

## 6. Unmanaged does not mean malicious

A blank device ID or an unmanaged and noncompliant state may result from BYOD, browser limitations, or missing device claims. It should increase attention, but it cannot independently establish compromise.

## 7. Post-authentication behavior is essential

A suspicious sign-in can appear harmless until the session creates forwarding, inbox rules, permissions, OAuth consent, or unusual downloads. Conversely, normal follow-on activity can materially reduce concern.

## 8. Session correlation improves confidence

Correlating user, IP, application, token, session ID, and time is stronger than comparing timestamps alone. Session-aware analysis helps distinguish user activity from unrelated service operations.

## 9. Cloud services generate activity against user mailboxes

Microsoft and authorized applications may access messages and attachments through service contexts. Additional IPs in audit data are not automatically additional user sessions.

Useful distinguishing fields include:

- `UserType`
- `ExternalAccess`
- `ClientAppId`
- `AppId`
- `TokenObjectId`
- `AADSessionId`
- `SessionId`
- `ClientInfoString`

## 10. MailItemsAccessed requires careful wording

`MailItemsAccessed` can be generated by folder loading, preview, synchronization, or service processing. It does not prove that every listed message was manually opened, downloaded, or exfiltrated.

## 11. Negative findings must be scoped

Write "not observed in the reviewed data" rather than "did not occur" when retention, exported fields, workloads, or time ranges are limited.

## 12. Privacy must be part of documentation

Public case studies should remove or generalize:

- Usernames and email addresses
- Employee and object IDs
- Tenant and session identifiers
- Public IP addresses
- Exact office locations
- Company-specific policy names
- Mailbox subjects and folder names
- Internal index and infrastructure names

## 13. Recommended process improvements

- Create a shared application-ID inventory.
- Normalize Entra sign-in fields across all ingestion paths.
- Add ASN, VPN, proxy, and corporate-egress enrichment.
- Automate the 30-day baseline comparison.
- Automate checks for inbox rules, forwarding, permissions, OAuth, and MFA changes.
- Capture the analyst verdict for detection tuning.
- Maintain a closure template that separates confirmed facts from assumptions.

## 14. Reusable conclusion pattern

A high-quality benign closure should explain:

1. Why the sign-in looked unusual
2. Why the observed attributes were compatible with history
3. How MFA and Conditional Access were validated
4. What the session did afterward
5. Which compromise indicators were checked
6. Why service activity was not attributed to an interactive actor
7. What limitations remained
